### ISSUE TITLE
How to cite this repo?

### ISSUE THREAD

**Issue by songyang-dev** [clir/clearnlp-guidelines#13]
Hi all, I'm writing a research paper and I'd like to cite this repo's list of dependencies. Is there a bibliography for this repo?

**Comment by jdchoi77** [comment]
It depends on which tools you are using. Can you specify which models you are using?

**Comment by XsongyangX** [comment]
I'm citing the list of dependency labels on this page.
https://github.com/clir/clearnlp-guidelines/blob/master/md/specifications/dependency_labels.md

**Comment by jdchoi77** [comment]
This is the technical report describing the CLEAR dependency:
https://www.researchgate.net/publication/324940566_Guidelines_for_the_CLEAR_Style_Constituent_to_Dependency_Conversion
