### ISSUE TITLE
NER specification

### ISSUE THREAD

**Issue by keighrim** [clir/clearnlp-guidelines#5]
Hi, 

Could anyone tell me where I can find the tagset for the default named entity recognizer?

**Comment by jtan25** [comment]
Hi 
The tagset can be found in the NERTag.java file 
https://github.com/clir/clearnlp/blob/376540ea025ccb14a97027737209290350bfd722/src/main/java/edu/emory/clir/clearnlp/ner/NERTag.java

**Comment by keighrim** [comment]
Thank you, @jtan25 . I'm closing the issue.
